export const StorageConstants = {
  KEYS: {
    AUTHENTICATION: {
      JWT_TOKEN: 'JWT_TOKEN',
      API_TOKEN: 'API_TOKEN',
    },
    PREFERENCES: {
      THEME: 'THEME_PREF',
      CONTAINER: 'CONTAINER_PREF',
    },
    ALERT_VISIBILITY: {
      CONTINUE_WITH_FAILED_DOWNLOADS: 'SHOW_CONTINUE_WITH_FAILED_DOWNLOADS_ALERT',
    },
  },
};
